name: onmessage
description: A stream wrapping JavaScript's `window.onmessage` that is safe to import even on platforms other than web.
repository: https://github.com/alexeyinkin/flutter-onmessage
version: 0.1.2

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  tidy: ^2.17.0
